# Generated by Django 5.1.4 on 2025-01-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
